title: "JOO's CFD Study"
description: "CFD portfolio for graduate lab applications: BFS reattachment and propeller-disk IGE studies."
url: "https://1001wngud.github.io"
baseurl: "" # If your repo name is NOT '1001wngud.github.io', change this to "/REPO-NAME"
repository: "1001wngud/1001wngud.github.io" # Change this if your site repo name is different

markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.28.0"

plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-sitemap

include:
  - _pages

collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/

defaults:
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false
      classes: wide

  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: false
      share: false
      classes: wide

  - scope:
      path: "bfs"
      type: pages
    values:
      layout: single
      author_profile: false
      classes: wide

  - scope:
      path: "ige"
      type: pages
    values:
      layout: single
      author_profile: false
      classes: wide

atom_feed:
  hide: true

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/1001wngud"
